name: Go CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    name: Lint Check (on PR)
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

  deploy:
    name: Deploy (on main push)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deployment
        run: echo "🚀 Deploying to production....."
